title: activeTAPI for Microsoft Dynamics 365
email: info@activeTAPI.net
description: > # this means to ignore newlines until "baseurl:"
  Format and validate telephone numbers

theme: jekyll-theme-slate

markdown: kramdown
